services:
  hhplus-mysql-test:
    image: mysql:8.0
    container_name: hhplus-mysql-test
    environment:
      LANGUAGE: ko_KR.UTF-8
      LANG: ko_KR.UTF-8
      MYSQL_ROOT_PASSWORD: 'test1234!'
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'UTC'
    ports:
      - '3307:3306'
    volumes:
      - ./infra/initdb:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password

  hhplus-redis-test:
    image: redis:latest
    container_name: hhplus-redis-test
    ports:
      - '6380:6379'
    tmpfs:
      - /data
